USE machineShop;
GO
ALTER TABLE Employee WITH CHECK
ADD CONSTRAINT FK_Zipcode FOREIGN KEY(ZipCodeID) REFERENCES ZipCode(ZipCodeID)
ON UPDATE CASCADE
GO
ALTER TABLE FinishedParts WITH CHECK
ADD CONSTRAINT FK_RawPartID FOREIGN KEY(RawPartID) REFERENCES RawParts(RawPartID)
ON UPDATE CASCADE
GO
ALTER TABLE WorkOrder WITH CHECK
ADD CONSTRAINT FK_FinishedPartID FOREIGN KEY(FinishedPartID) REFERENCES FinishedParts(FinishedPartID)
ON UPDATE CASCADE
GO
ALTER TABLE DailyRun WITH CHECK
ADD CONSTRAINT FK_EmployeeID FOREIGN KEY(EmployeeID) REFERENCES Employee(EmployeeID)
ON UPDATE CASCADE
GO
ALTER TABLE DailyRun WITH CHECK
ADD CONSTRAINT FK_WorkOrderID FOREIGN KEY(WorkOrderID) REFERENCES WorkOrder(WorkOrderID)
ON UPDATE CASCADE
GO
ALTER TABLE DailyRun WITH CHECK
ADD CONSTRAINT FK_MachineID FOREIGN KEY(MachineID) REFERENCES Machine(MachineID)
ON UPDATE CASCADE
GO

